#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

### For remove operations, the core deprovisions every resource defined
### in the manifest **after** this script runs -- this includes removing
### $install_dir and $data_dir (the latter only if --purge was used).

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi
ynh_config_remove_systemd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
